# -*- coding: utf-8 -*-
"""final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1knfI3C2Gisi7cPSGlVrq-LHk1r5IPWYd

Step 1: Importing libraries
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score, classification_report

from sklearn.ensemble import ExtraTreesClassifier, GradientBoostingClassifier
from sklearn.neural_network import MLPClassifier

from imblearn.combine import SMOTEENN

import warnings
warnings.filterwarnings("ignore")

"""Step 2: Loading Dataset

"""

import pandas as pd

df = pd.read_csv("/content/Dengue Fever Hematological Dataset.csv")
# Encode Result
if df["Result"].dtype == "object":
    df["Result"] = df["Result"].map({"negative": 0, "positive": 1})

# Encode Gender
if df["Gender"].dtype == "object":
    df["Gender"] = df["Gender"].map({"Male": 1, "Female": 0})

print("Dataset Shape:", df.shape)
df.head()

print(y.value_counts())

"""Step 3: Feature Engineering

"""

#1. Neutrophil-to-Lymphocyte Ratio
df["NLR"] = df["Neutrophils(%)"] / (df["Lymphocytes(%)"] + 1) #Viral infection when low NLR
# helps to detect infection type

#2. Platelet-to-WBC Ratio
df["PLR"] = df["Total Platelet Count(/cumm)"] / (df["Total WBC count(/cumm)"] + 1) #Their relationship gives additional information about infection.

#3. RBC × HCT
df["RBC_HCT"] = df["RBC"] * df["HCT(%)"] # hemoconcentration : the blood becomes more concentrated because of plasma leckage

#4. MPV × Platelet
df["MPV_PLT"] = df["MPV(fl)"] * df["Total Platelet Count(/cumm)"] #helps detect platelet dynamics.

df.head()

"""Step 4: Separate Raw and Ratio Features"""

raw_features = [
    col for col in df.columns
    if col not in ["Result", "NLR", "PLR", "RBC_HCT", "MPV_PLT"]
]

ratio_features = ["NLR", "PLR", "RBC_HCT", "MPV_PLT"]

X_raw = df[raw_features]
X_ratio = df[ratio_features]
y = df["Result"]

print("Raw Features:", raw_features)
print("Ratio Features:", ratio_features)

print("Shape of X_raw:", X_raw.shape)
print("Shape of X_ratio:", X_ratio.shape)

"""Step 5: Apply SMOTEENN (Synthetic minority over-sampling technique)"""

# SMOTE + ENN (edited nearest neighbour) is used for class imbalance

from imblearn.combine import SMOTEENN

X_combined = pd.concat([X_raw, X_ratio], axis=1)

smoteenn = SMOTEENN(random_state=42)
X_res, y_res = smoteenn.fit_resample(X_combined, y)

print("After SMOTEENN:", pd.Series(y_res).value_counts())

print("Shape of X_res:", X_res.shape)
print("Shape of y_res:", y_res.shape)

"""Step 6: Train Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X_res,
    y_res,
    test_size=0.2,
    stratify=y_res, # it keeps the train and test values same without class imbalance
    random_state=42
)

"""Step 7: Separate Raw and Ratio After Split"""

X_train_raw = X_train[raw_features]
X_train_ratio = X_train[ratio_features]

X_test_raw = X_test[raw_features]
X_test_ratio = X_test[ratio_features]

"""Step 8: Scaling"""

# Mean = 0 and standard deviation = 1 (It uses z score)
scaler_raw = StandardScaler()
scaler_ratio = StandardScaler()

X_train_raw = scaler_raw.fit_transform(X_train_raw)
X_test_raw = scaler_raw.transform(X_test_raw)

X_train_ratio = scaler_ratio.fit_transform(X_train_ratio)
X_test_ratio = scaler_ratio.transform(X_test_ratio)

"""Step 9: Train Raw Path Model"""

# Extremely Randomized Trees

# it works well on tabular dataset, takes whole dataset for each tree.
# random split and reduces over fitting

model_raw = ExtraTreesClassifier(
    n_estimators=500, # 500 decision trees
    random_state=42
)

model_raw.fit(X_train_raw, y_train)

"""Step 10: Train Ratio Path Model"""

# works well on the combined features
model_ratio = GradientBoostingClassifier(
    n_estimators=300,
    learning_rate=0.05,
    random_state=42
)

model_ratio.fit(X_train_ratio, y_train)

"""Step 11: Probability Fusion"""

prob_raw_train = model_raw.predict_proba(X_train_raw)
prob_ratio_train = model_ratio.predict_proba(X_train_ratio)

fusion_train = np.hstack((prob_raw_train, prob_ratio_train))

prob_raw_test = model_raw.predict_proba(X_test_raw)
prob_ratio_test = model_ratio.predict_proba(X_test_ratio)

fusion_test = np.hstack((prob_raw_test, prob_ratio_test))

"""Step 12: Train Meta Learner"""

# MLP- Multi layer perceptron

meta_model = MLPClassifier(
    hidden_layer_sizes=(32, 16),  # 1st hidden layer-32 and 2nd -16
    max_iter=500,
    random_state=42
)

meta_model.fit(fusion_train, y_train)

"""Step 13: Evaluate"""

y_pred = meta_model.predict(fusion_test)
y_prob = meta_model.predict_proba(fusion_test)[:, 1]

# roc - auc (receiver operating characteristics - area under the curve )
print("Accuracy:", accuracy_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

from sklearn.metrics import roc_curve
import matplotlib.pyplot as plt

fpr, tpr, _ = roc_curve(y_test, y_prob)

plt.plot(fpr, tpr)
plt.plot([0,1],[0,1],'--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve")
plt.show()

import pandas as pd

importance = model_raw.feature_importances_
feature_importance = pd.Series(importance, index=raw_features)

feature_importance.sort_values(ascending=False).head(10)

actual = y_test.iloc[0:5].values
predictions = meta_model.predict(fusion_test[0:5])

for i in range(len(predictions)):
    actual_label = "Dengue Positive" if actual[i] == 1 else "Dengue Negative"
    predicted_label = "Dengue Positive" if predictions[i] == 1 else "Dengue Negative"

    print(f"Patient {i+1} → Actual: {actual_label} | Predicted: {predicted_label}")

import pandas as pd
from sklearn.ensemble import ExtraTreesClassifier
import joblib

df = pd.read_csv("Dengue Fever Hematological Dataset.csv")

df["Result"] = df["Result"].map({"negative":0,"positive":1})

X = df[
[
"Total Platelet Count(/cumm)",
"Total WBC count(/cumm)",
"Neutrophils(%)",
"Lymphocytes(%)"
]
]

y = df["Result"]

model = ExtraTreesClassifier(n_estimators=200, random_state=42)
model.fit(X,y)

joblib.dump(model,"dengue_simple_model.pkl")

model = joblib.load("dengue_simple_model.pkl")

pip install shap

import shap
import matplotlib.pyplot as plt

shap.initjs()

# Define input data
input_data = X.iloc[0]

explainer = shap.TreeExplainer(model)
shap_values = explainer.shap_values(input_data)

shap.force_plot(explainer.expected_value[1], shap_values[:,1], input_data)